#https://leetcode.com/problems/find-the-difference/
"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y" 
"""

class Solution(object):
    def findTheDifference(self, s, t):
        countt = {}
        

        for char in t:
            countt[char] = countt.get(char, 0) + 1
        
    
        for char in s:
            countt[char] -= 1

        
        for char, count in countt.items():
            if count == 1:
                return char